package main

import "testing"

// TestAllFunctionsTypedCorrectly è¦çå¨é¨ 76 ä¸ªå½æ°
// åä¸èæ¬å·²ç¨çå®ç¼è¯å¨éªè¯ç¼è¯éè¿ï¼EXIT=0ï¼ã
func TestAllFunctionsTypedCorrectly(t *testing.T) {
	code := `
_VM_BATTLE_START {
    VM_BanCard("small_fire")
    VM_BanAllCard()
    VM_CannelBanCard("small_fire")
    VM_BanWeapon()
    VM_BanSuperWeapon()
    VM_BanShield()
    VM_SetCardLevelCap(1)
    VM_SetCardShapeCap(1)
    VM_SetCardSkillCap(1)
    VM_SetMaxSlots(1)
    VM_ShellPrint(1)
    VM_ShowNotice(1)
    VM_CreatePlatform(1, 1, 1, 1, 1, 1, 1, "s")
    VM_SpawnPlant("small_fire", 1, 1, 1, 1, 1)
    VM_SpawnEnemy("normal_mouse", 1, 1)
    VM_SpawnBoss("normal_mouse", 1, 1)
    VM_LoadSprite("s")
    VM_SpawnObject("obstacle", 1, 1)
    VM_SetProp(1, "s", 1)
    VM_GetWave()
    VM_GetSubwave()
    VM_GetProp(1, "s")
    VM_GetKilledProp("s")
    VM_GetLastBoss()
    VM_GetLastCreatedEnemy()
    VM_GetLastKilledEnemy()
    VM_GetLastCreatedCard()
    VM_GetLastDestroyedCard()
    VM_GetFlame()
    VM_SetFlame(1)
    VM_SetTerrain(1, 1, "s")
    VM_ClearPlants(1, 1)
    VM_Random(1, 1)
    VM_GetLastIdlePlatform()
    VM_SetPlatformParams(1, 1, 1, 1, 1)
    VM_SetMapBackground("s", 0.5)
    VM_SetDrawSlot(1, "s", 1, 1, 0.5)
    VM_GetLoadedSpriteName(1)
    VM_GameWin()
    VM_GameLose()
    VM_SetDrawSlot_front(1, "s", 1, 1, 0.5)
    VM_SpawnCats(1)
    VM_ClearMapObjects(1, 1, "s")
    VM_BanGem("s")
    VM_SetRowFeature(1, "s")
    VM_ClearPlantsByType("s")
    VM_WakePlants(1, 1)
    VM_SetCardProp(1, 1, "s", "s", 1)
    VM_SetEnemyProp("s", "s", 1)
    VM_ShowNoticeDur(1)
    VM_SetEventEnabled(1)
    VM_RefreshPlatformSnapshots()
    VM_GetMouseX()
    VM_GetMouseY()
    VM_GetMouseCol()
    VM_GetMouseRow()
    VM_GetTerrain(1, 1)
    VM_GetMousePressed(1)
    VM_GetKeyDown("s")
    VM_GetKeyPressed("s")
    VM_GetEnemyCount()
    VM_GetPlantCount()
    VM_GetPlantCountAt(1, 1, "s")
    VM_PlaySound("s")
    VM_IsUndefined(1)
    VM_IsDestroyed(1)
    VM_LoadSound("s")
    VM_Floor(1)
    VM_Ceil(1)
    VM_SpawnBatMouse(1, 1)
    VM_GetTimeLimit()
    VM_SetTimeLimit(1)
    VM_GetPlantAt(1, 1, "s")
    VM_SwapPlants(1, 1, 1, 1)
    VM_SwapPlantRects(1, 1, 1, 1, 1, 1)
    VM_CompactColumn(1)
    VM_CompactRow(1)
    VM_CompactColumnRev(1)
    VM_CompactRowRev(1)
    VM_SpawnPlantsRandom(1, 1, 1, 1, 1, 1, 1, "s", "s", "s", "s", "s", "s", "s", "s", "s")
    VM_CreateButton(1, 1, "s", 0.5, 1, 1, 1)
    VM_GetLastClickedButton()
    VM_LoadSpriteFrames("s", 1)
    VM_ApplyPlantLevel(1)
    VM_LoadSpritePerm("s", 1)
    VM_FreeSpritePerm("s")
    VM_SetCardSlotProp("s", "s", 1)
    VM_CalcCardSlotProp("s", "s", 1, 1)
    VM_GetCardSlotCount()
    VM_GetPreviewCard()
    VM_AliasSprite("s", "s")
    VM_LoadSpriteFrames_Ex("s", 1, 1, 1)
    VM_ArrayGet("s", 1)
    VM_ArraySet("s", 1, 1)
    VM_ArrayDel("s", 1)
    VM_ArrayADD("s", 1)
    VM_ArraySize("s")
    VM_ArrayClear("s")
    VM_ArrayClearAll()
    VM_SetDrawSlotEx(1, "s", 1, 1, 0.5, 0.5, 0.5, 0.5)
    VM_SetDrawSlotEx_front(1, "s", 1, 1, 0.5, 0.5, 0.5, 0.5)
    VM_SetWaveAuto(1)
    VM_SetWave(1, 1)
    VM_GetCurCard()
    VM_EnemyInRange(1, 1, 1, 1, "s")
    VM_GetHomingTarget("s")
    VM_GetInstancesInRange("s", 1, 1, 1, 1, "s", "s")
    VM_CreateInstance("s", 0.5, 0.5)
    VM_LoadSpritePerm_Ex("s", 1, 1, 1)
    VM_SetShovelFlameRate(0.5)
    VM_BulletScreenAdd(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
    VM_DrawSpriteExt(1, 1, 1, 1, 1, 1, 1, 1)
    VM_RunStep(1, 1)
    VM_DestroyInstance(1)
    VM_GetCardProp("s", "s")
    VM_CanPlace("s", 1, 1)
    VM_CallFunc("VM_GetFlame")
    VM_FuncExists("s")
    VM_FuncDesc("s")
    VM_SpriteExists("s")
    VM_AliasSpritePerm("s", "s")
    VM_ArrayExists("s")
    VM_CellCount("enemy_array", 1, 1)
    VM_CellItem("enemy_array", 1, 1, 0)
    VM_CellContains("enemy_array", 1, 1, 1)
    VM_ArrayContains("enemy_array", 1)
    VM_InstArrayExists(1, "a")
    VM_InstArraySize(1, "a")
    VM_InstArrayItem(1, "a", 0)
    VM_InstArraySet(1, "a", 0, 1)
    VM_InstArrayAdd(1, "a", 1)
    VM_InstArrayDel(1, "a", 0)
    VM_InstArrayClear(1, "a")
    VM_InstArrayContains(1, "a", 1)
    VM_HomingBulletAdd("spr_bullet", 1, 1, 1, 10, 1, "all", "", "", "", 0)
    VM_DamageEnemy(1, 1, "normal")
    VM_DamageEnemyAsh(1, 1, "normal")
    VM_BulletScreenAdd_Ex("spr_bullet", 1, 0, 1.6, 1, 1, 1, 8, 0, 1, 1, 0 - 1, "normal", "", "", "normal", 5, 0)
    VM_BulletScreenAdd_Exs("spr_bullet", 1, 0, 1.6, 1, 1, 1, 8, 0, 1, 1, 0 - 1, "normal", "", "", "normal", 5, 0, 0 - 1, 0.15)
}
`
	for _, d := range lintScript(code) {
		if d.Severity == "error" {
			t.Errorf("all funcs valid call should not error: line %d [%s] %s", d.Line, d.Severity, d.Message)
		}
	}
}
