// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckCode(arg1:string):Promise<Array<main.Diagnostic>>;

export function Compile(arg1:string):Promise<main.CompileResult>;

export function GetBlockInfo(arg1:string,arg2:number):Promise<main.BlockHint>;

export function GetCompilerInfo():Promise<string>;

export function GetEditorMeta():Promise<main.EditorMeta>;

export function GetHelp():Promise<string>;

export function GetTemplate():Promise<string>;

export function GetUpdateLog():Promise<string>;

export function LogJsError(arg1:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function PickOpenFile():Promise<string>;

export function PickSaveFile(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SetDirty(arg1:boolean):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
