// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckCode(arg1) {
  return window['go']['main']['App']['CheckCode'](arg1);
}

export function Compile(arg1) {
  return window['go']['main']['App']['Compile'](arg1);
}

export function GetBlockInfo(arg1, arg2) {
  return window['go']['main']['App']['GetBlockInfo'](arg1, arg2);
}

export function GetCompilerInfo() {
  return window['go']['main']['App']['GetCompilerInfo']();
}

export function GetEditorMeta() {
  return window['go']['main']['App']['GetEditorMeta']();
}

export function GetHelp() {
  return window['go']['main']['App']['GetHelp']();
}

export function GetTemplate() {
  return window['go']['main']['App']['GetTemplate']();
}

export function GetUpdateLog() {
  return window['go']['main']['App']['GetUpdateLog']();
}

export function LogJsError(arg1) {
  return window['go']['main']['App']['LogJsError'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function PickOpenFile() {
  return window['go']['main']['App']['PickOpenFile']();
}

export function PickSaveFile(arg1) {
  return window['go']['main']['App']['PickSaveFile'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SetDirty(arg1) {
  return window['go']['main']['App']['SetDirty'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
